# Generated by Django 4.2.3 on 2023-07-24 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productmodel_delete_dba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='first_name',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='last_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
